@startuml
Class01 <.. Class02 : Dependency\n依赖
Class05 <|-- Class06 : Generalization\n继承、泛化
Class07 <|.. Class08 : Realization\n接口实现
Class03 -- Class04 : Association\n关联
Class09 o-- Class10 : Aggregation\n聚合
Class11 *-- Class12 : Composite\n组合
@enduml