@startuml
'https://plantuml.com/class-diagram

class Object {
    #native Object clone()
}

interface Cloneable

class Concreate extends Object  implements Cloneable {
    #Object clone()
}

class Client

Client ..> Concreate

@enduml